openapi: 3.1.0
info:
  title: Reference Sequences Service
  description: |-
    Provide info about reference sequences
  contact:
    email: dan.fornika@bccdc.ca
  license:
    name: GNU Affero General Public License v3.0
    url: "https://www.gnu.org/licenses/agpl-3.0.txt"
  version: 0.1.0
tags:
  - name: reference-genomes
    description: Info about reference genomes
  - name: reference-plasmids
    description: Info about reference sequences for targeted regions
  - name: targeted-sequences
    description: Info about sequenced libraries
paths:
  /reference-genomes:
    get:
      tags:
        - reference-genomes
      summary: Get a list of reference genomes
      description: Get a list of reference genomes
      operationId: getReferenceGenomeList
      parameters:
        - name: sort
          schema:
            type: string
        - name: page
          schema:
            type: string
        - name: filter
          schema:
            type: string
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReferenceGenomeJSONArray'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ReferenceGenomeJSONAPIArray'
    post:
      tags:
        - reference-genomes
      summary: Add a new reference genome
      operationId: addReferenceGenome
      responses:
        '201':
          description: Created
  /reference-genomes/{referenceGenomeId}:
    get:
      tags:
        - reference-genomes
      summary: Get a reference genome by ID
      description: Get a reference genome by ID
      operationId: getReferenceGenome
    delete:
      tags:
        - reference-genomes
      summary: Delete a reference genome
      operationId: deleteReferenceGenome
  /reference-plasmids:
    get:
      tags:
        - reference-plasmids
    post:
      tags:
        - reference-plasmids
  /reference-plasmids/{referencePlasmidId}:
    get:
      tags:
        - reference-plasmids
    delete:
      tags:
        - reference-plasmids
  /reference-targeted-sequences:
    get:
      tags:
        - targeted-sequences
    post:
      tags:
        - targeted-sequences
  /reference-targeted-sequences/{referenceTargetedSequenceId}:
    get:
      tags:
        - targeted-sequences
    delete:
      tags:
        - targeted-sequences
components:
  schemas:
    ReferenceGenomeJSON:
      type: object
      properties:
        id:
          type: string
    ReferenceGenomeJSONArray:
      type: array
      items:
        $ref: '#/components/schemas/ReferenceGenomeJSON'
    ReferenceGenomeJSONAPI:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
          properties:
            source:
              type: string
            genus_name:
              type: string
            genus_taxonomy_id:
              type: string
            species_name:
              type: string
            species_taxonomy_id:
              type: string
            genome_size_bp:
              type: integer
            gc_percent:
              type: number
            num_contigs:
              type: integer
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
    ReferenceGenomeJSONAPIArray:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceGenomeJSONAPI'
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
            first:
              type: string
              format: uri
            last:
              type: string
              format: uri
            prev:
              type: string
              format: uri
            next:
              type: string
              format: uri
    ServerErrorJSON:
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
    ServerErrorJSONArray:
      type: array
      items:
        $ref: '#/components/schemas/ServerErrorJSON'
    ServerErrorJSONAPI:
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
    ServerErrorJSONAPIArray:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ServerErrorJSONAPI'
  requestBodies:
    ReferenceGenome:
      description: Reference genome object that needs to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReferenceGenomeJSON'
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ReferenceGenomeJSONAPI'
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: oauth/authorize
          scopes:
            reference-sequences:read: read reference sequences
            reference-sequences:write: modify reference sequences
    api_key:
      type: apiKey
      name: api_key
      in: header
